# Generated by Django 2.1 on 2018-08-18 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
